[mypy]
strict = True
warn_return_any = True
warn_unused_ignores = True
disallow_untyped_defs = True
check_untyped_defs = True

[mypy-numpy]
ignore_missing_imports = True

[mypy-pydantic.*]
ignore_missing_imports = True

[mypy-pydantic]
ignore_missing_imports = True

[mypy-llm_sdk.*]
ignore_missing_imports = True

[mypy-llm_sdk]
ignore_missing_imports = True
